# ==============================================================================
# Nginx Static Container for Web Companion Preview
# ==============================================================================
FROM nginx:alpine

COPY frontend/web_preview /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
